#! /bin/csh -x
#
# Copyright (c) 2018 Oracle and/or its affiliates. All rights reserved.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Distribution License v. 1.0, which is available at
# http://www.eclipse.org/org/documents/edl-v10.php.
#
# SPDX-License-Identifier: BSD-3-Clause
#

setenv ORB ${CORBA_WS}/build/rename/ee/build/release/lib/bundles-archive.zip
setenv DEST ${GFV3_WORK}/glassfish4

cd ${DEST}
unzip -o ${ORB}

