#! /bin/csh -x
#
# Copyright (c) 2018 Oracle and/or its affiliates. All rights reserved.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Distribution License v. 1.0, which is available at
# http://www.eclipse.org/org/documents/edl-v10.php.
#
# SPDX-License-Identifier: BSD-3-Clause
#

setenv BUILD ${GFV3_WS}
if ("$1" == "") then
    setenv RUN ${GFV3_WORK}
else
    setenv RUN ${GFV3_WORK}/$1
endif

rm ${RUN}/glassfish.zip
rm -rf ${RUN}/glassfish4
cp ${BUILD}/distributions/glassfish/target/glassfish.zip ${RUN}
cd ${RUN}
unzip -q glassfish.zip
