#! /bin/csh
#
# Copyright (c) 2018, 2020 Oracle and/or its affiliates. All rights reserved.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v. 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0, or the Eclipse Distribution License
# v. 1.0 which is available at
# http://www.eclipse.org/org/documents/edl-v10.php.
#
# This Source Code may also be made available under the following Secondary
# Licenses when the conditions for such availability set forth in the Eclipse
# Public License v. 2.0 are satisfied: GNU General Public License v2.0
# w/Classpath exception which is available at
# https://www.gnu.org/software/classpath/license.html.
#
# SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause OR GPL-2.0 WITH
# Classpath-exception-2.0
#

setenv BUILD ${GFV3_WS}
setenv RUN ${GFV3_WORK}
setenv MAVEN ~/.m2/repository
setenv GROUPID org/glassfish/security
setenv DEST ${RUN}/glassfish4/glassfish/modules
setenv VERSION 3.1-SNAPSHOT

cd ${MAVEN}/${GROUPID}

pushd ejb.security/${VERSION}
cp ejb.security-${VERSION}.jar ${DEST}/ejb.security.jar

