#!/bin/sh -x
#
# Copyright (c) 2018 Oracle and/or its affiliates. All rights reserved.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Distribution License v. 1.0, which is available at
# http://www.eclipse.org/org/documents/edl-v10.php.
#
# SPDX-License-Identifier: BSD-3-Clause
#

#JAVA_HOME=$1
JPS=$JAVA_HOME/bin/jps
PROC_NAME=$1
OSNAME=`uname -a | awk '{ print $1 }'`
echo "$OSNAME"

kill_processes() {
    PROCESS_NAME=$1
    case $OSNAME in
	AIX*) PIDS=`ps -ef | grep $PROCESS_NAME |grep glassfish.jar| awk '{ print $2 }' | xargs`;;
        *) PIDS=`$JAVA_HOME/bin/jps -mlVv | grep $PROCESS_NAME | awk '{ print $1 }' | xargs`;;
    esac

    for PID in $PIDS ;
        do
        case $OSNAME in
           CYGWIN*) taskkill /F /T /PID $PID;;
           *) kill -9 $PID;;
        esac
    done
}

kill_processes $PROC_NAME

