#! /bin/csh
#
# Copyright (c) 2018 Oracle and/or its affiliates. All rights reserved.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Distribution License v. 1.0, which is available at
# http://www.eclipse.org/org/documents/edl-v10.php.
#
# SPDX-License-Identifier: BSD-3-Clause
#

foreach f (`jps | grep ASMain | gawk '{print $1}'`)
    # echo $f
    kill -9 $f
end
foreach f (`jps | grep Broker | gawk '{print $1}'`)
    # echo $f
    kill -9 $f
end
foreach f (`jps | grep DerbyControl | gawk '{print $1}'`)
    # echo $f
    kill -9 $f
end
