#!/bin/sh -x
#
# Copyright (c) 2018, 2020 Oracle and/or its affiliates. All rights reserved.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v. 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0, or the Eclipse Distribution License
# v. 1.0 which is available at
# http://www.eclipse.org/org/documents/edl-v10.php.
#
# This Source Code may also be made available under the following Secondary
# Licenses when the conditions for such availability set forth in the Eclipse
# Public License v. 2.0 are satisfied: GNU General Public License v2.0
# w/Classpath exception which is available at
# https://www.gnu.org/software/classpath/license.html.
#
# SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause OR GPL-2.0 WITH
# Classpath-exception-2.0
#

#JAVA_HOME=$1
JPS=$JAVA_HOME/bin/jps
PROC_NAME=$1
OSNAME=`uname -a | awk '{ print $1 }'`
echo "$OSNAME"

kill_processes() {
    PROCESS_NAME=$1
    case $OSNAME in
	AIX*) PIDS=`ps -ef | grep $PROCESS_NAME |grep glassfish.jar| awk '{ print $2 }' | xargs`;;
        *) PIDS=`$JAVA_HOME/bin/jps -mlVv | grep $PROCESS_NAME | awk '{ print $1 }' | xargs`;;
    esac

    for PID in $PIDS ;
        do
        case $OSNAME in
           CYGWIN*) taskkill /F /T /PID $PID;;
           *) kill -9 $PID;;
        esac
    done
}

kill_processes $PROC_NAME

