package org.omg.CORBA;


/**
* org/omg/CORBA/AttributeMode.java .
* IGNORE Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlj/src/main/java/com/sun/tools/corba/ee/idl/ir.idl
* IGNORE Sunday, January 21, 2018 1:54:23 PM EST
*/

public class AttributeMode implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 2;
  private static org.omg.CORBA.AttributeMode[] __array = new org.omg.CORBA.AttributeMode [__size];

  public static final int _ATTR_NORMAL = 0;
  public static final org.omg.CORBA.AttributeMode ATTR_NORMAL = new org.omg.CORBA.AttributeMode(_ATTR_NORMAL);
  public static final int _ATTR_READONLY = 1;
  public static final org.omg.CORBA.AttributeMode ATTR_READONLY = new org.omg.CORBA.AttributeMode(_ATTR_READONLY);

  public int value ()
  {
    return __value;
  }

  public static org.omg.CORBA.AttributeMode from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected AttributeMode (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class AttributeMode
