package org.omg.CORBA;


/**
* org/omg/CORBA/ConstantDefOperations.java .
* IGNORE Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlj/src/main/java/com/sun/tools/corba/ee/idl/ir.idl
* IGNORE Sunday, January 21, 2018 1:54:23 PM EST
*/

public interface ConstantDefOperations  extends org.omg.CORBA.ContainedOperations
{
  org.omg.CORBA.TypeCode type ();
  org.omg.CORBA.IDLType type_def ();
  void type_def (org.omg.CORBA.IDLType newType_def);
  org.omg.CORBA.Any value ();
  void value (org.omg.CORBA.Any newValue);
} // interface ConstantDefOperations
