package org.omg.CORBA;


/**
* org/omg/CORBA/DefinitionKind.java .
* IGNORE Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlj/src/main/java/com/sun/tools/corba/ee/idl/ir.idl
* IGNORE Sunday, January 21, 2018 1:54:22 PM EST
*/

public class DefinitionKind implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 24;
  private static org.omg.CORBA.DefinitionKind[] __array = new org.omg.CORBA.DefinitionKind [__size];

  public static final int _dk_none = 0;
  public static final org.omg.CORBA.DefinitionKind dk_none = new org.omg.CORBA.DefinitionKind(_dk_none);
  public static final int _dk_all = 1;
  public static final org.omg.CORBA.DefinitionKind dk_all = new org.omg.CORBA.DefinitionKind(_dk_all);
  public static final int _dk_Attribute = 2;
  public static final org.omg.CORBA.DefinitionKind dk_Attribute = new org.omg.CORBA.DefinitionKind(_dk_Attribute);
  public static final int _dk_Constant = 3;
  public static final org.omg.CORBA.DefinitionKind dk_Constant = new org.omg.CORBA.DefinitionKind(_dk_Constant);
  public static final int _dk_Exception = 4;
  public static final org.omg.CORBA.DefinitionKind dk_Exception = new org.omg.CORBA.DefinitionKind(_dk_Exception);
  public static final int _dk_Interface = 5;
  public static final org.omg.CORBA.DefinitionKind dk_Interface = new org.omg.CORBA.DefinitionKind(_dk_Interface);
  public static final int _dk_Module = 6;
  public static final org.omg.CORBA.DefinitionKind dk_Module = new org.omg.CORBA.DefinitionKind(_dk_Module);
  public static final int _dk_Operation = 7;
  public static final org.omg.CORBA.DefinitionKind dk_Operation = new org.omg.CORBA.DefinitionKind(_dk_Operation);
  public static final int _dk_Typedef = 8;
  public static final org.omg.CORBA.DefinitionKind dk_Typedef = new org.omg.CORBA.DefinitionKind(_dk_Typedef);
  public static final int _dk_Alias = 9;
  public static final org.omg.CORBA.DefinitionKind dk_Alias = new org.omg.CORBA.DefinitionKind(_dk_Alias);
  public static final int _dk_Struct = 10;
  public static final org.omg.CORBA.DefinitionKind dk_Struct = new org.omg.CORBA.DefinitionKind(_dk_Struct);
  public static final int _dk_Union = 11;
  public static final org.omg.CORBA.DefinitionKind dk_Union = new org.omg.CORBA.DefinitionKind(_dk_Union);
  public static final int _dk_Enum = 12;
  public static final org.omg.CORBA.DefinitionKind dk_Enum = new org.omg.CORBA.DefinitionKind(_dk_Enum);
  public static final int _dk_Primitive = 13;
  public static final org.omg.CORBA.DefinitionKind dk_Primitive = new org.omg.CORBA.DefinitionKind(_dk_Primitive);
  public static final int _dk_String = 14;
  public static final org.omg.CORBA.DefinitionKind dk_String = new org.omg.CORBA.DefinitionKind(_dk_String);
  public static final int _dk_Sequence = 15;
  public static final org.omg.CORBA.DefinitionKind dk_Sequence = new org.omg.CORBA.DefinitionKind(_dk_Sequence);
  public static final int _dk_Array = 16;
  public static final org.omg.CORBA.DefinitionKind dk_Array = new org.omg.CORBA.DefinitionKind(_dk_Array);
  public static final int _dk_Repository = 17;
  public static final org.omg.CORBA.DefinitionKind dk_Repository = new org.omg.CORBA.DefinitionKind(_dk_Repository);
  public static final int _dk_Wstring = 18;
  public static final org.omg.CORBA.DefinitionKind dk_Wstring = new org.omg.CORBA.DefinitionKind(_dk_Wstring);
  public static final int _dk_Fixed = 19;
  public static final org.omg.CORBA.DefinitionKind dk_Fixed = new org.omg.CORBA.DefinitionKind(_dk_Fixed);
  public static final int _dk_Value = 20;
  public static final org.omg.CORBA.DefinitionKind dk_Value = new org.omg.CORBA.DefinitionKind(_dk_Value);
  public static final int _dk_ValueBox = 21;
  public static final org.omg.CORBA.DefinitionKind dk_ValueBox = new org.omg.CORBA.DefinitionKind(_dk_ValueBox);
  public static final int _dk_ValueMember = 22;
  public static final org.omg.CORBA.DefinitionKind dk_ValueMember = new org.omg.CORBA.DefinitionKind(_dk_ValueMember);
  public static final int _dk_Native = 23;
  public static final org.omg.CORBA.DefinitionKind dk_Native = new org.omg.CORBA.DefinitionKind(_dk_Native);

  public int value ()
  {
    return __value;
  }

  public static org.omg.CORBA.DefinitionKind from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected DefinitionKind (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class DefinitionKind
