package org.omg.CORBA;


/**
* org/omg/CORBA/EnumDef.java .
* IGNORE Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlj/src/main/java/com/sun/tools/corba/ee/idl/ir.idl
* IGNORE Sunday, January 21, 2018 1:54:23 PM EST
*/

public interface EnumDef extends EnumDefOperations, org.omg.CORBA.TypedefDef, org.omg.CORBA.portable.IDLEntity 
{
} // interface EnumDef
