package org.omg.CORBA;


/**
* org/omg/CORBA/ExceptionDef.java .
* IGNORE Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlj/src/main/java/com/sun/tools/corba/ee/idl/ir.idl
* IGNORE Sunday, January 21, 2018 1:54:23 PM EST
*/

public interface ExceptionDef extends ExceptionDefOperations, org.omg.CORBA.Contained, org.omg.CORBA.Container
{
} // interface ExceptionDef
