package org.omg.CORBA;

/**
* org/omg/CORBA/ExceptionDefHolder.java .
* IGNORE Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlj/src/main/java/com/sun/tools/corba/ee/idl/ir.idl
* IGNORE Sunday, January 21, 2018 1:54:23 PM EST
*/

public final class ExceptionDefHolder implements org.omg.CORBA.portable.Streamable
{
  public org.omg.CORBA.ExceptionDef value = null;

  public ExceptionDefHolder ()
  {
  }

  public ExceptionDefHolder (org.omg.CORBA.ExceptionDef initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.omg.CORBA.ExceptionDefHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.omg.CORBA.ExceptionDefHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.omg.CORBA.ExceptionDefHelper.type ();
  }

}
