package org.omg.CORBA;


/**
* org/omg/CORBA/Initializer.java .
* IGNORE Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlj/src/main/java/com/sun/tools/corba/ee/idl/ir.idl
* IGNORE Sunday, January 21, 2018 1:54:22 PM EST
*/

public final class Initializer implements org.omg.CORBA.portable.IDLEntity
{
  public org.omg.CORBA.StructMember members[] = null;

  public Initializer ()
  {
  } // ctor

  public Initializer (org.omg.CORBA.StructMember[] _members)
  {
    members = _members;
  } // ctor

} // class Initializer
