package org.omg.CORBA;


/**
* org/omg/CORBA/IRObjectOperations.java .
* IGNORE Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlj/src/main/java/com/sun/tools/corba/ee/idl/ir.idl
* IGNORE Sunday, January 21, 2018 1:54:22 PM EST
*/

public interface IRObjectOperations 
{

  // read interface
  org.omg.CORBA.DefinitionKind def_kind ();

  // write interface
  void destroy ();
} // interface IRObjectOperations
