package org.omg.CORBA;


/**
* org/omg/CORBA/NativeDef.java .
* IGNORE Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlj/src/main/java/com/sun/tools/corba/ee/idl/ir.idl
* IGNORE Sunday, January 21, 2018 1:54:24 PM EST
*/


// orbos 98-01-18: Objects By Value -- end
public interface NativeDef extends NativeDefOperations, org.omg.CORBA.TypedefDef, org.omg.CORBA.portable.IDLEntity 
{
} // interface NativeDef
