package org.omg.CORBA;

/**
* org/omg/CORBA/NativeDefHolder.java .
* IGNORE Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlj/src/main/java/com/sun/tools/corba/ee/idl/ir.idl
* IGNORE Sunday, January 21, 2018 1:54:24 PM EST
*/


// orbos 98-01-18: Objects By Value -- end
public final class NativeDefHolder implements org.omg.CORBA.portable.Streamable
{
  public org.omg.CORBA.NativeDef value = null;

  public NativeDefHolder ()
  {
  }

  public NativeDefHolder (org.omg.CORBA.NativeDef initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.omg.CORBA.NativeDefHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.omg.CORBA.NativeDefHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.omg.CORBA.NativeDefHelper.type ();
  }

}
