package org.omg.CORBA;


/**
* org/omg/CORBA/OperationDefOperations.java .
* IGNORE Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlj/src/main/java/com/sun/tools/corba/ee/idl/ir.idl
* IGNORE Sunday, January 21, 2018 1:54:23 PM EST
*/

public interface OperationDefOperations  extends org.omg.CORBA.ContainedOperations
{
  org.omg.CORBA.TypeCode result ();
  org.omg.CORBA.IDLType result_def ();
  void result_def (org.omg.CORBA.IDLType newResult_def);
  org.omg.CORBA.ParameterDescription[] params ();
  void params (org.omg.CORBA.ParameterDescription[] newParams);
  org.omg.CORBA.OperationMode mode ();
  void mode (org.omg.CORBA.OperationMode newMode);
  String[] contexts ();
  void contexts (String[] newContexts);
  org.omg.CORBA.ExceptionDef[] exceptions ();
  void exceptions (org.omg.CORBA.ExceptionDef[] newExceptions);
} // interface OperationDefOperations
