package org.omg.CORBA;


/**
* org/omg/CORBA/ParameterDescription.java .
* IGNORE Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlj/src/main/java/com/sun/tools/corba/ee/idl/ir.idl
* IGNORE Sunday, January 21, 2018 1:54:23 PM EST
*/

public final class ParameterDescription implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public org.omg.CORBA.TypeCode type = null;
  public org.omg.CORBA.IDLType type_def = null;
  public org.omg.CORBA.ParameterMode mode = null;

  public ParameterDescription ()
  {
  } // ctor

  public ParameterDescription (String _name, org.omg.CORBA.TypeCode _type, org.omg.CORBA.IDLType _type_def, org.omg.CORBA.ParameterMode _mode)
  {
    name = _name;
    type = _type;
    type_def = _type_def;
    mode = _mode;
  } // ctor

} // class ParameterDescription
