package org.omg.CORBA;


/**
* org/omg/CORBA/PrimitiveKind.java .
* IGNORE Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlj/src/main/java/com/sun/tools/corba/ee/idl/ir.idl
* IGNORE Sunday, January 21, 2018 1:54:22 PM EST
*/

public class PrimitiveKind implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 16;
  private static org.omg.CORBA.PrimitiveKind[] __array = new org.omg.CORBA.PrimitiveKind [__size];

  public static final int _pk_null = 0;
  public static final org.omg.CORBA.PrimitiveKind pk_null = new org.omg.CORBA.PrimitiveKind(_pk_null);
  public static final int _pk_void = 1;
  public static final org.omg.CORBA.PrimitiveKind pk_void = new org.omg.CORBA.PrimitiveKind(_pk_void);
  public static final int _pk_short = 2;
  public static final org.omg.CORBA.PrimitiveKind pk_short = new org.omg.CORBA.PrimitiveKind(_pk_short);
  public static final int _pk_long = 3;
  public static final org.omg.CORBA.PrimitiveKind pk_long = new org.omg.CORBA.PrimitiveKind(_pk_long);
  public static final int _pk_ushort = 4;
  public static final org.omg.CORBA.PrimitiveKind pk_ushort = new org.omg.CORBA.PrimitiveKind(_pk_ushort);
  public static final int _pk_ulong = 5;
  public static final org.omg.CORBA.PrimitiveKind pk_ulong = new org.omg.CORBA.PrimitiveKind(_pk_ulong);
  public static final int _pk_float = 6;
  public static final org.omg.CORBA.PrimitiveKind pk_float = new org.omg.CORBA.PrimitiveKind(_pk_float);
  public static final int _pk_double = 7;
  public static final org.omg.CORBA.PrimitiveKind pk_double = new org.omg.CORBA.PrimitiveKind(_pk_double);
  public static final int _pk_boolean = 8;
  public static final org.omg.CORBA.PrimitiveKind pk_boolean = new org.omg.CORBA.PrimitiveKind(_pk_boolean);
  public static final int _pk_char = 9;
  public static final org.omg.CORBA.PrimitiveKind pk_char = new org.omg.CORBA.PrimitiveKind(_pk_char);
  public static final int _pk_octet = 10;
  public static final org.omg.CORBA.PrimitiveKind pk_octet = new org.omg.CORBA.PrimitiveKind(_pk_octet);
  public static final int _pk_any = 11;
  public static final org.omg.CORBA.PrimitiveKind pk_any = new org.omg.CORBA.PrimitiveKind(_pk_any);
  public static final int _pk_TypeCode = 12;
  public static final org.omg.CORBA.PrimitiveKind pk_TypeCode = new org.omg.CORBA.PrimitiveKind(_pk_TypeCode);
  public static final int _pk_Principal = 13;
  public static final org.omg.CORBA.PrimitiveKind pk_Principal = new org.omg.CORBA.PrimitiveKind(_pk_Principal);
  public static final int _pk_string = 14;
  public static final org.omg.CORBA.PrimitiveKind pk_string = new org.omg.CORBA.PrimitiveKind(_pk_string);
  public static final int _pk_objref = 15;
  public static final org.omg.CORBA.PrimitiveKind pk_objref = new org.omg.CORBA.PrimitiveKind(_pk_objref);

  public int value ()
  {
    return __value;
  }

  public static org.omg.CORBA.PrimitiveKind from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected PrimitiveKind (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class PrimitiveKind
