package org.omg.CORBA;


/**
* org/omg/CORBA/PUBLIC_MEMBER.java .
* IGNORE Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlj/src/main/java/com/sun/tools/corba/ee/idl/ir.idl
* IGNORE Sunday, January 21, 2018 1:54:22 PM EST
*/

public interface PUBLIC_MEMBER
{
  public static final short value = (short)(1);
}
