package org.omg.CORBA;


/**
* org/omg/CORBA/RepositoryOperations.java .
* IGNORE Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlj/src/main/java/com/sun/tools/corba/ee/idl/ir.idl
* IGNORE Sunday, January 21, 2018 1:54:23 PM EST
*/

public interface RepositoryOperations  extends org.omg.CORBA.ContainerOperations
{

  // read interface
  org.omg.CORBA.Contained lookup_id (String search_id);
  org.omg.CORBA.PrimitiveDef get_primitive (org.omg.CORBA.PrimitiveKind kind);

  // write interface
  org.omg.CORBA.StringDef create_string (int bound);
  org.omg.CORBA.SequenceDef create_sequence (int bound, org.omg.CORBA.IDLType element_type);
  org.omg.CORBA.ArrayDef create_array (int length, org.omg.CORBA.IDLType element_type);
} // interface RepositoryOperations
