package org.omg.CORBA;

/**
* org/omg/CORBA/StringDefHolder.java .
* IGNORE Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlj/src/main/java/com/sun/tools/corba/ee/idl/ir.idl
* IGNORE Sunday, January 21, 2018 1:54:23 PM EST
*/

public final class StringDefHolder implements org.omg.CORBA.portable.Streamable
{
  public org.omg.CORBA.StringDef value = null;

  public StringDefHolder ()
  {
  }

  public StringDefHolder (org.omg.CORBA.StringDef initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.omg.CORBA.StringDefHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.omg.CORBA.StringDefHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.omg.CORBA.StringDefHelper.type ();
  }

}
