package org.omg.CORBA;


/**
* org/omg/CORBA/StructDefOperations.java .
* IGNORE Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlj/src/main/java/com/sun/tools/corba/ee/idl/ir.idl
* IGNORE Sunday, January 21, 2018 1:54:23 PM EST
*/

public interface StructDefOperations  extends org.omg.CORBA.TypedefDefOperations, org.omg.CORBA.ContainerOperations
{
  org.omg.CORBA.StructMember[] members ();
  void members (org.omg.CORBA.StructMember[] newMembers);
} // interface StructDefOperations
