package org.omg.CORBA;

/**
* org/omg/CORBA/ValueMemberDefHolder.java .
* IGNORE Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlj/src/main/java/com/sun/tools/corba/ee/idl/ir.idl
* IGNORE Sunday, January 21, 2018 1:54:23 PM EST
*/


// orbos 98-01-18: Objects By Value -- begin
public final class ValueMemberDefHolder implements org.omg.CORBA.portable.Streamable
{
  public org.omg.CORBA.ValueMemberDef value = null;

  public ValueMemberDefHolder ()
  {
  }

  public ValueMemberDefHolder (org.omg.CORBA.ValueMemberDef initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.omg.CORBA.ValueMemberDefHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.omg.CORBA.ValueMemberDefHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.omg.CORBA.ValueMemberDefHelper.type ();
  }

}
