package org.omg.CORBA;


/**
* org/omg/CORBA/ValueMember.java .
* IGNORE Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlj/src/main/java/com/sun/tools/corba/ee/idl/ir.idl
* IGNORE Sunday, January 21, 2018 1:54:22 PM EST
*/

public final class ValueMember implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public String id = null;
  public String defined_in = null;
  public String version = null;
  public org.omg.CORBA.TypeCode type = null;
  public org.omg.CORBA.IDLType type_def = null;
  public short access = (short)0;

  public ValueMember ()
  {
  } // ctor

  public ValueMember (String _name, String _id, String _defined_in, String _version, org.omg.CORBA.TypeCode _type, org.omg.CORBA.IDLType _type_def, short _access)
  {
    name = _name;
    id = _id;
    defined_in = _defined_in;
    version = _version;
    type = _type;
    type_def = _type_def;
    access = _access;
  } // ctor

} // class ValueMember
