package org.omg.CORBA;


/**
* org/omg/CORBA/ValueDefSeqHolder.java .
* IGNORE Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlj/src/main/java/com/sun/tools/corba/ee/idl/ir.idl
* IGNORE Sunday, January 21, 2018 1:54:22 PM EST
*/

public final class ValueDefSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public org.omg.CORBA.ValueDef value[] = null;

  public ValueDefSeqHolder ()
  {
  }

  public ValueDefSeqHolder (org.omg.CORBA.ValueDef[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.omg.CORBA.ValueDefSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.omg.CORBA.ValueDefSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.omg.CORBA.ValueDefSeqHelper.type ();
  }

}
