package org.omg.CORBA;


/**
* org/omg/CORBA/ValueDef.java .
* IGNORE Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlj/src/main/java/com/sun/tools/corba/ee/idl/ir.idl
* IGNORE Sunday, January 21, 2018 1:54:24 PM EST
*/

public interface ValueDef extends ValueDefOperations, org.omg.CORBA.Container, org.omg.CORBA.Contained, org.omg.CORBA.IDLType
{
} // interface ValueDef
