package org.omg.CORBA;


/**
* org/omg/CORBA/ValueBoxDefOperations.java .
* IGNORE Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlj/src/main/java/com/sun/tools/corba/ee/idl/ir.idl
* IGNORE Sunday, January 21, 2018 1:54:24 PM EST
*/

public interface ValueBoxDefOperations  extends org.omg.CORBA.IDLTypeOperations
{
  org.omg.CORBA.IDLType original_type_def ();
  void original_type_def (org.omg.CORBA.IDLType newOriginal_type_def);
} // interface ValueBoxDefOperations
