/*
 * Copyright (c) 1997, 2020 Oracle and/or its affiliates.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0, or the Eclipse Distribution License
 * v. 1.0 which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License v. 2.0 are satisfied: GNU General Public License v2.0
 * w/Classpath exception which is available at
 * https://www.gnu.org/software/classpath/license.html.
 *
 * SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause OR GPL-2.0 WITH
 * Classpath-exception-2.0
 */

package fake.omega;


/**
* fake/omega/Juliet.java
* Generated by the IBM IDL-to-Java compiler (portable), version "3.0"
* from d:/java/java/idl/omega/Juliet.idl
* 01 May 1999 14:09:28 o'clock GMT+00:00
*/

public class Juliet implements org.omg.CORBA.portable.ValueBase
{
    public int value;
    public Juliet (int initial)
    {
        value = initial;
    }

    public String[] _truncatable_ids() {
        return fake.omega.JulietHelper.get_instance().get_truncatable_base_ids();
    }

} // class Juliet
