/*
 * Copyright (c) 1997, 2020 Oracle and/or its affiliates.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0, or the Eclipse Distribution License
 * v. 1.0 which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License v. 2.0 are satisfied: GNU General Public License v2.0
 * w/Classpath exception which is available at
 * https://www.gnu.org/software/classpath/license.html.
 *
 * SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause OR GPL-2.0 WITH
 * Classpath-exception-2.0
 */

package fake.omega;


/**
* fake/omega/JulietHelper.java
* Generated by the IBM IDL-to-Java compiler (portable), version "3.0"
* from d:/java/java/idl/omega/Juliet.idl
* 01 May 1999 14:09:29 o'clock GMT+00:00
*/

public final class JulietHelper implements com.sun.org.omg.CORBA.portable.ValueHelper
{
    private static String  _id = "IDL:phoney.pfix/omega/Juliet:1.0";

    private static JulietHelper helper = new JulietHelper ();

    private static String[] _truncatable_ids = {
        _id   };

    public JulietHelper()
    {
    }

    public static void insert (org.omg.CORBA.Any a, fake.omega.Juliet that)
    {
        org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
        a.type (type ());
        write (out, that);
        a.read_value (out.create_input_stream (), type ());
    }

    public static fake.omega.Juliet extract (org.omg.CORBA.Any a)
    {
        return read (a.create_input_stream ());
    }

    private static org.omg.CORBA.TypeCode __typeCode = null;
    private static boolean __active = false;
    synchronized public static org.omg.CORBA.TypeCode type ()
    {
        if (__typeCode == null)
            {
                synchronized (org.omg.CORBA.TypeCode.class)
                    {
                        if (__typeCode == null)
                            {
                                if (__active)
                                    {
                                        return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
                                    }
                                __active = true;
                                __typeCode = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
                                __typeCode = org.omg.CORBA.ORB.init ().create_value_box_tc (_id, "Juliet", __typeCode);
                                __active = false;
                            }
                    }
            }
        return __typeCode;
    }

    public static String id ()
    {
        return _id;
    }

    public static fake.omega.Juliet read (org.omg.CORBA.portable.InputStream istream)
    {
        return (fake.omega.Juliet) ((org.omg.CORBA_2_3.portable.InputStream) istream).read_value (get_instance());
    }

    public java.io.Serializable read_value (org.omg.CORBA.portable.InputStream istream)
    {
        int tmp = istream.read_long ();
        return new fake.omega.Juliet (tmp);
    }

    public static void write (org.omg.CORBA.portable.OutputStream ostream, fake.omega.Juliet value)
    {
        ((org.omg.CORBA_2_3.portable.OutputStream) ostream).write_value (value, get_instance());
    }

    public void write_value (org.omg.CORBA.portable.OutputStream ostream, java.io.Serializable obj)
    {
        fake.omega.Juliet value  = (fake.omega.Juliet) obj;
        ostream.write_long (value.value);
    }

    public String get_id ()
    {
        return _id;
    }

    public org.omg.CORBA.TypeCode get_type ()
    {
        return type ();
    }

    public static com.sun.org.omg.CORBA.portable.ValueHelper get_instance ()
    {
        return helper;
    }

    public Class get_class ()
    {
        return fake.omega.Juliet.class;
    }

    public String[] get_truncatable_base_ids ()
    {
        return _truncatable_ids;
    }

}
