/*
 * Copyright (c) 1997, 2020 Oracle and/or its affiliates.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0, or the Eclipse Distribution License
 * v. 1.0 which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License v. 2.0 are satisfied: GNU General Public License v2.0
 * w/Classpath exception which is available at
 * https://www.gnu.org/software/classpath/license.html.
 *
 * SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause OR GPL-2.0 WITH
 * Classpath-exception-2.0
 */

// CosTSInteroperation module, as on 11/04/2000
// CORBAservices, Transaction Service V1.2 (RTF Working Draft)
// http://www.omg.org/cgi-bin/doc?ptc/00-09-04.pdf

#pragma prefix "omg.org"

#include <corba.idl>
#include "IOP.idl"

module CosTSInteroperation {

    // Commented out since J2EE does not need them.
    //const IOP::ComponentId TAG_TRANSACTION_POLICY = 26;
    //struct TransactionPolicyComponent {
    //    TransactionPolicyValue value;
    //};

    const IOP::ComponentId TAG_OTS_POLICY = 31;
    const IOP::ComponentId TAG_INV_POLICY = 32;
};

