/*
 * Copyright (c) 1997, 2018 Oracle and/or its affiliates. All rights reserved.
 * Copyright (c) 1998-1999 IBM Corp. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Distribution License v. 1.0, which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

package javax.rmi.CORBA.serialization;

/**
* DateDefaultFactory.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from java/util/Date.idl
* 01 June 1999 20:22:16 o'clock GMT+00:00
*/

public class DateDefaultFactory implements DateValueFactory {

  public Date create__ ()
  {
    return new DateImpl ();
  }

  public Date create__long__long__long (int arg0, int arg1, int arg2)
  {
    return new DateImpl (arg0, arg1, arg2);
  }

  public Date create__long__long__long__long__long (int arg0, int arg1, int arg2, int arg3, int arg4)
  {
    return new DateImpl (arg0, arg1, arg2, arg3, arg4);
  }

  public Date create__long__long__long__long__long__long (int arg0, int arg1, int arg2, int arg3, int arg4, int arg5)
  {
    return new DateImpl (arg0, arg1, arg2, arg3, arg4, arg5);
  }

  public Date create__long_long (long arg0)
  {
    return new DateImpl (arg0);
  }

  public Date create__CORBA_WStringValue (String arg0)
  {
    return new DateImpl (arg0);
  }

  public java.io.Serializable read_value (org.omg.CORBA_2_3.portable.InputStream is)
  {
    return is.read_value(new DateImpl());
  }
}
