/*
 * Copyright (c) 1997, 2018 Oracle and/or its affiliates. All rights reserved.
 * Copyright (c) 1998-1999 IBM Corp. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Distribution License v. 1.0, which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

package javax.rmi.CORBA.serialization;

/**
* DateValueFactory.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from java/util/Date.idl
* 01 June 1999 20:22:16 o'clock GMT+00:00
*/

public interface DateValueFactory extends org.omg.CORBA.portable.ValueFactory
{
  Date create__ ();
  Date create__long__long__long (int arg0, int arg1, int arg2);
  Date create__long__long__long__long__long (int arg0, int arg1, int arg2, int arg3, int arg4);
  Date create__long__long__long__long__long__long (int arg0, int arg1, int arg2, int arg3, int arg4, int arg5);
  Date create__long_long (long arg0);
  Date create__CORBA_WStringValue (String arg0);
}
