package org.omg.CORBA.ValueDefPackage;

/**
* org/omg/CORBA/ValueDefPackage/FullValueDescriptionHolder.java .
* IGNORE Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlj/src/main/java/com/sun/tools/corba/ee/idl/ir.idl
* IGNORE Sunday, January 21, 2018 1:54:24 PM EST
*/

public final class FullValueDescriptionHolder implements org.omg.CORBA.portable.Streamable
{
  public org.omg.CORBA.ValueDefPackage.FullValueDescription value = null;

  public FullValueDescriptionHolder ()
  {
  }

  public FullValueDescriptionHolder (org.omg.CORBA.ValueDefPackage.FullValueDescription initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.omg.CORBA.ValueDefPackage.FullValueDescriptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.omg.CORBA.ValueDefPackage.FullValueDescriptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.omg.CORBA.ValueDefPackage.FullValueDescriptionHelper.type ();
  }

}
