/*
 * Copyright (c) 1997, 2020 Oracle and/or its affiliates.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0, or the Eclipse Distribution License
 * v. 1.0 which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License v. 2.0 are satisfied: GNU General Public License v2.0
 * w/Classpath exception which is available at
 * https://www.gnu.org/software/classpath/license.html.
 *
 * SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause OR GPL-2.0 WITH
 * Classpath-exception-2.0
 */

package hopper.h4620926;

import test.Test;
import corba.framework.*;
import java.util.*;

/**
 */
public class ConcurrentServantActivatorTest extends CORBATest
{
    public static String[] idlFiles = { "Hello.idl" } ;

    // Define the .java files that need to be compiled.  Any
    // java files generated by compiling IDL will automatically be
    // compiled with these.
    public static String[] javaFiles = { "Client.java", "Server.java" };

    // This is the main method defining the test.  All tests
    // should have this.
    protected void doTest() throws Throwable
    {
        Options.addIDLCompilerArgs( "-fall" ) ;
        Options.setIDLFiles( idlFiles ) ;
        Options.setJavaFiles(javaFiles);

        // Run the compilers.
        compileIDLFiles() ;
        compileJavaFiles();

        Controller orbd = createORBD() ;
        orbd.start() ;

        Controller server = createServer( "hopper.h4620926.Server" ) ;
        server.start() ;

        Controller client = createClient("hopper.h4620926.Client");
        client.start();

        // Wait for the client to finish for up to 2 minutes, then
        // throw an exception.
        client.waitFor(120000);

        // Make sure all the processes are shut down.
        client.stop();
        server.stop() ;
        orbd.stop() ;
    }
}

