/*
 * Copyright (c) 1997, 2018 Oracle and/or its affiliates. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Distribution License v. 1.0, which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

module ClientRequestInfo
{
    exception ExampleException { string reason; };

    interface hello
    {
        string sayHello();
        string saySystemException();
        void sayUserException() raises (ExampleException);
        oneway void sayOneway();
        string sayArguments( in string arg1, in long arg2, in boolean arg3 );
        void clearInvoked();
        boolean wasInvoked();
        void resetServant();
    };
};

