/*
 * Copyright (c) 1997, 2020 Oracle and/or its affiliates.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0, or the Eclipse Distribution License
 * v. 1.0 which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License v. 2.0 are satisfied: GNU General Public License v2.0
 * w/Classpath exception which is available at
 * https://www.gnu.org/software/classpath/license.html.
 *
 * SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause OR GPL-2.0 WITH
 * Classpath-exception-2.0
 */

//
// Tests nested type declarations whose type definitions are in 
// inherited super interfaces.
//
module TestIdlj {

    interface A1 {
        enum A1_Enum { X1, X2, X3 };
    };

    interface A2 : A1 {};

    interface A3 : A2 {
        struct A3_Struct { A1_Enum x; };
    };

    interface A4: A2 {
        typedef A1_Enum A4_Enum;
    };

    interface A5: A4 {
        typedef A4_Enum A5_Enum;
        struct A5_Struct {
            A4_Enum x;
            A5_Enum y;
        };
    };

    interface B1 {
        typedef long B1_long;
    };

    interface B2 : B1 {};

    interface B3 : B2 {
        exception BB_Exception { B1_long x; };
    };

    interface B4 : B2 {
        typedef B1_long B4_long;
    };

    interface B5 : B4 {
        typedef B4_long B5_long;
        exception BB_Exception { 
            B4_long  x;
            B5_long y;
        };
    };
};
