package org.omg.CORBA.ContainedPackage;


/**
* org/omg/CORBA/ContainedPackage/Description.java .
* IGNORE Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlj/src/main/java/com/sun/tools/corba/ee/idl/ir.idl
* IGNORE Sunday, January 21, 2018 1:54:22 PM EST
*/

public final class Description implements org.omg.CORBA.portable.IDLEntity
{
  public org.omg.CORBA.DefinitionKind kind = null;
  public org.omg.CORBA.Any value = null;

  public Description ()
  {
  } // ctor

  public Description (org.omg.CORBA.DefinitionKind _kind, org.omg.CORBA.Any _value)
  {
    kind = _kind;
    value = _value;
  } // ctor

} // class Description
