/*
 * Copyright (c) 1997, 2018 Oracle and/or its affiliates. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Distribution License v. 1.0, which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

package fake.omega;


/**
* fake/omega/Juliet.java
* Generated by the IBM IDL-to-Java compiler (portable), version "3.0"
* from d:/java/java/idl/omega/Juliet.idl
* 01 May 1999 14:09:28 o'clock GMT+00:00
*/

public class Juliet implements org.omg.CORBA.portable.ValueBase
{
    public int value;
    public Juliet (int initial)
    {
        value = initial;
    }

    public String[] _truncatable_ids() {
        return fake.omega.JulietHelper.get_instance().get_truncatable_base_ids();
    }

} // class Juliet
