/*
 * Copyright (c) 1997, 2018 Oracle and/or its affiliates. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Distribution License v. 1.0, which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

package com.sun.corba.ee.impl.protocol.giopmsgheaders;


/**
* com/sun/corba/ee/impl/protocol/giopmsgheaders/IORAddressingInfo.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from ../../../../../../../src/share/classes/com/sun/corba/ee/GiopIDL/g.idl
* Sunday, June 4, 2000 5:18:54 PM PDT
*/

public final class IORAddressingInfo implements org.omg.CORBA.portable.IDLEntity
{
  public int selected_profile_index = (int)0;
  public org.omg.IOP.IOR ior = null;

  public IORAddressingInfo ()
  {
  } // ctor

  public IORAddressingInfo (int _selected_profile_index, org.omg.IOP.IOR _ior)
  {
    selected_profile_index = _selected_profile_index;
    ior = _ior;
  } // ctor

} // class IORAddressingInfo
