package org.glassfish.idlj.CORBAServerTestPackage;

/**
* org/glassfish/idlj/CORBAServerTestPackage/AnExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "4.1"
* from /Users/rgold/projects/glassfish/glassfish-corba/idlj/src/main/idl/org/glassfish/idlj/CORBAServerTest.idl
* Monday, January 29, 2018 11:19:41 AM EST
*/

public final class AnExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public org.glassfish.idlj.CORBAServerTestPackage.AnException value = null;

  public AnExceptionHolder ()
  {
  }

  public AnExceptionHolder (org.glassfish.idlj.CORBAServerTestPackage.AnException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.glassfish.idlj.CORBAServerTestPackage.AnExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.glassfish.idlj.CORBAServerTestPackage.AnExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.glassfish.idlj.CORBAServerTestPackage.AnExceptionHelper.type ();
  }

}
