package org.glassfish.idlj.CORBAServerTestPackage;

/**
* org/glassfish/idlj/CORBAServerTestPackage/MungedExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "4.1"
* from /Users/rgold/projects/glassfish/glassfish-corba/idlj/src/main/idl/org/glassfish/idlj/CORBAServerTest.idl
* Monday, January 29, 2018 11:19:41 AM EST
*/

public final class MungedExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public org.glassfish.idlj.CORBAServerTestPackage.MungedException value = null;

  public MungedExceptionHolder ()
  {
  }

  public MungedExceptionHolder (org.glassfish.idlj.CORBAServerTestPackage.MungedException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.glassfish.idlj.CORBAServerTestPackage.MungedExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.glassfish.idlj.CORBAServerTestPackage.MungedExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.glassfish.idlj.CORBAServerTestPackage.MungedExceptionHelper.type ();
  }

}
