package org.glassfish.idlj;


/**
* org/glassfish/idlj/_CORBAServerTestImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "4.1"
* from /Users/rgold/projects/glassfish/glassfish-corba/idlj/src/main/idl/org/glassfish/idlj/CORBAServerTest.idl
* Monday, January 29, 2018 11:19:41 AM EST
*/

public abstract class _CORBAServerTestImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements org.glassfish.idlj.CORBAServerTest, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _CORBAServerTestImplBase ()
  {
  }

  private static java.util.Map<String,Integer> _methods = new java.util.HashMap<String,Integer> ();
  static
  {
    _methods.put ("test_primitive", 0);
    _methods.put ("test_oneway", 1);
    _methods.put ("test_any", 2);
    _methods.put ("test_out", 3);
    _methods.put ("test_inout", 4);
    _methods.put ("test_transaction", 5);
    _methods.put ("test_subject", 6);
    _methods.put ("test_exception", 7);
    _methods.put ("test_exception2", 8);
    _methods.put ("test_widestring", 9);
    _methods.put ("test_timeout", 10);
    _methods.put ("test_value", 11);
    _methods.put ("test_union", 12);
    _methods.put ("test_struct", 13);
    _methods.put ("test_seq", 14);
    _methods.put ("test_long_seq", 15);
    _methods.put ("test_POA", 16);
    _methods.put ("cleanup_POA", 17);
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = _methods.get($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // org/glassfish/idlj/CORBAServerTest/test_primitive
       {
         String s = in.read_string ();
         int l = in.read_long ();
         String $result = null;
         $result = this.test_primitive (s, l);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // org/glassfish/idlj/CORBAServerTest/test_oneway
       {
         String s = in.read_string ();
         int l = in.read_long ();
         this.test_oneway (s, l);
         out = $rh.createReply();
         break;
       }

       case 2:  // org/glassfish/idlj/CORBAServerTest/test_any
       {
         org.omg.CORBA.Any a = in.read_any ();
         org.omg.CORBA.Any $result = null;
         $result = this.test_any (a);
         out = $rh.createReply();
         out.write_any ($result);
         break;
       }

       case 3:  // org/glassfish/idlj/CORBAServerTest/test_out
       {
         org.omg.CORBA.StringHolder s = new org.omg.CORBA.StringHolder ();
         this.test_out (s);
         out = $rh.createReply();
         out.write_string (s.value);
         break;
       }

       case 4:  // org/glassfish/idlj/CORBAServerTest/test_inout
       {
         org.omg.CORBA.AnyHolder a = new org.omg.CORBA.AnyHolder ();
         a.value = in.read_any ();
         this.test_inout (a);
         out = $rh.createReply();
         out.write_any (a.value);
         break;
       }

       case 5:  // org/glassfish/idlj/CORBAServerTest/test_transaction
       {
         this.test_transaction ();
         out = $rh.createReply();
         break;
       }

       case 6:  // org/glassfish/idlj/CORBAServerTest/test_subject
       {
         this.test_subject ();
         out = $rh.createReply();
         break;
       }

       case 7:  // org/glassfish/idlj/CORBAServerTest/test_exception
       {
         try {
           this.test_exception ();
           out = $rh.createReply();
         } catch (org.glassfish.idlj.CORBAServerTestPackage.AnException $ex) {
           out = $rh.createExceptionReply ();
           org.glassfish.idlj.CORBAServerTestPackage.AnExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 8:  // org/glassfish/idlj/CORBAServerTest/test_exception2
       {
         try {
           this.test_exception2 ();
           out = $rh.createReply();
         } catch (org.glassfish.idlj.CORBAServerTestPackage.MungedException $ex) {
           out = $rh.createExceptionReply ();
           org.glassfish.idlj.CORBAServerTestPackage.MungedExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 9:  // org/glassfish/idlj/CORBAServerTest/test_widestring
       {
         String w = in.read_wstring ();
         String $result = null;
         $result = this.test_widestring (w);
         out = $rh.createReply();
         out.write_wstring ($result);
         break;
       }

       case 10:  // org/glassfish/idlj/CORBAServerTest/test_timeout
       {
         int timeout = in.read_long ();
         String $result = null;
         $result = this.test_timeout (timeout);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 11:  // org/glassfish/idlj/CORBAServerTest/test_value
       {
         String w = org.omg.CORBA.WStringValueHelper.read (in);
         String $result = null;
         $result = this.test_value (w);
         out = $rh.createReply();
         org.omg.CORBA.WStringValueHelper.write (out, $result);
         break;
       }

       case 12:  // org/glassfish/idlj/CORBAServerTest/test_union
       {
         org.glassfish.idlj.CORBAUnionHolder u = new org.glassfish.idlj.CORBAUnionHolder ();
         u.value = org.glassfish.idlj.CORBAUnionHelper.read (in);
         org.glassfish.idlj.CORBAUnion $result = null;
         $result = this.test_union (u);
         out = $rh.createReply();
         org.glassfish.idlj.CORBAUnionHelper.write (out, $result);
         org.glassfish.idlj.CORBAUnionHelper.write (out, u.value);
         break;
       }

       case 13:  // org/glassfish/idlj/CORBAServerTest/test_struct
       {
         org.glassfish.idlj.CORBAStruct s = org.glassfish.idlj.CORBAStructHelper.read (in);
         org.glassfish.idlj.CORBAStructHolder os = new org.glassfish.idlj.CORBAStructHolder ();
         org.glassfish.idlj.CORBAStruct $result = null;
         $result = this.test_struct (s, os);
         out = $rh.createReply();
         org.glassfish.idlj.CORBAStructHelper.write (out, $result);
         org.glassfish.idlj.CORBAStructHelper.write (out, os.value);
         break;
       }

       case 14:  // org/glassfish/idlj/CORBAServerTest/test_seq
       {
         org.glassfish.idlj.CORBASeqHolder seq = new org.glassfish.idlj.CORBASeqHolder ();
         seq.value = org.glassfish.idlj.CORBASeqHelper.read (in);
         org.glassfish.idlj.CORBAStruct $result[] = null;
         $result = this.test_seq (seq);
         out = $rh.createReply();
         org.glassfish.idlj.CORBASeqHelper.write (out, $result);
         org.glassfish.idlj.CORBASeqHelper.write (out, seq.value);
         break;
       }

       case 15:  // org/glassfish/idlj/CORBAServerTest/test_long_seq
       {
         org.glassfish.idlj.LongSeqHolder seq = new org.glassfish.idlj.LongSeqHolder ();
         seq.value = org.glassfish.idlj.LongSeqHelper.read (in);
         int $result[] = null;
         $result = this.test_long_seq (seq);
         out = $rh.createReply();
         org.glassfish.idlj.LongSeqHelper.write (out, $result);
         org.glassfish.idlj.LongSeqHelper.write (out, seq.value);
         break;
       }

       case 16:  // org/glassfish/idlj/CORBAServerTest/test_POA
       {
         String name = in.read_string ();
         org.omg.CORBA.Object $result = null;
         $result = this.test_POA (name);
         out = $rh.createReply();
         org.omg.CORBA.ObjectHelper.write (out, $result);
         break;
       }

       case 17:  // org/glassfish/idlj/CORBAServerTest/cleanup_POA
       {
         String name = in.read_string ();
         this.cleanup_POA (name);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:org/glassfish/idlj/CORBAServerTest:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _CORBAServerTestImplBase
