package org.glassfish.idlj;


/**
* org/glassfish/idlj/CORBAServerTestHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "4.1"
* from /Users/rgold/projects/glassfish/glassfish-corba/idlj/src/main/idl/org/glassfish/idlj/CORBAServerTest.idl
* Monday, January 29, 2018 11:19:41 AM EST
*/

abstract public class CORBAServerTestHelper
{
  private static String  _id = "IDL:org/glassfish/idlj/CORBAServerTest:1.0";

  public static void insert (org.omg.CORBA.Any a, org.glassfish.idlj.CORBAServerTest that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static org.glassfish.idlj.CORBAServerTest extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (org.glassfish.idlj.CORBAServerTestHelper.id (), "CORBAServerTest");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static org.glassfish.idlj.CORBAServerTest read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CORBAServerTestStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, org.glassfish.idlj.CORBAServerTest value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static org.glassfish.idlj.CORBAServerTest narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof org.glassfish.idlj.CORBAServerTest)
      return (org.glassfish.idlj.CORBAServerTest)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      org.glassfish.idlj._CORBAServerTestStub stub = new org.glassfish.idlj._CORBAServerTestStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static org.glassfish.idlj.CORBAServerTest unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof org.glassfish.idlj.CORBAServerTest)
      return (org.glassfish.idlj.CORBAServerTest)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      org.glassfish.idlj._CORBAServerTestStub stub = new org.glassfish.idlj._CORBAServerTestStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
