/*
 * Copyright (c) 2020 Oracle and/or its affiliates. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0, or the Eclipse Distribution License
 * v. 1.0 which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License v. 2.0 are satisfied: GNU General Public License v2.0
 * w/Classpath exception which is available at
 * https://www.gnu.org/software/classpath/license.html.
 *
 * SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause OR GPL-2.0 WITH
 * Classpath-exception-2.0
 */

package org.glassfish.idlj;

/**
* org/glassfish/idlj/CORBAEnum.java .
* Generated by the IDL-to-Java compiler (portable), version "4.1"
* from /Users/rgold/projects/glassfish/glassfish-corba/idlj/src/main/idl/org/glassfish/idlj/CORBAServerTest.idl
* Monday, January 29, 2018 11:19:41 AM EST
*/

public class CORBAEnum implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 3;
  private static org.glassfish.idlj.CORBAEnum[] __array = new org.glassfish.idlj.CORBAEnum [__size];

  public static final int _ONE = 0;
  public static final org.glassfish.idlj.CORBAEnum ONE = new org.glassfish.idlj.CORBAEnum(_ONE);
  public static final int _TWO = 1;
  public static final org.glassfish.idlj.CORBAEnum TWO = new org.glassfish.idlj.CORBAEnum(_TWO);
  public static final int _THREE = 2;
  public static final org.glassfish.idlj.CORBAEnum THREE = new org.glassfish.idlj.CORBAEnum(_THREE);

  public int value ()
  {
    return __value;
  }

  public static org.glassfish.idlj.CORBAEnum from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected CORBAEnum (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class CORBAEnum
