/*
 * Copyright (c) 2020 Oracle and/or its affiliates. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0, or the Eclipse Distribution License
 * v. 1.0 which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License v. 2.0 are satisfied: GNU General Public License v2.0
 * w/Classpath exception which is available at
 * https://www.gnu.org/software/classpath/license.html.
 *
 * SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause OR GPL-2.0 WITH
 * Classpath-exception-2.0
 */

package org.glassfish.idlj;

/**
* org/glassfish/idlj/CORBAServerTestOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "4.1"
* from /Users/rgold/projects/glassfish/glassfish-corba/idlj/src/main/idl/org/glassfish/idlj/CORBAServerTest.idl
* Monday, January 29, 2018 11:19:41 AM EST
*/

public interface CORBAServerTestOperations 
{
  String test_primitive (String s, int l);
  void test_oneway (String s, int l);
  org.omg.CORBA.Any test_any (org.omg.CORBA.Any a);
  void test_out (org.omg.CORBA.StringHolder s);
  void test_inout (org.omg.CORBA.AnyHolder a);
  void test_transaction ();
  void test_subject ();
  void test_exception () throws org.glassfish.idlj.CORBAServerTestPackage.AnException;
  void test_exception2 () throws org.glassfish.idlj.CORBAServerTestPackage.MungedException;
  String test_widestring (String w);
  String test_timeout (int timeout);
  String test_value (String w);
  org.glassfish.idlj.CORBAUnion test_union (org.glassfish.idlj.CORBAUnionHolder u);
  org.glassfish.idlj.CORBAStruct test_struct (org.glassfish.idlj.CORBAStruct s, org.glassfish.idlj.CORBAStructHolder os);
  org.glassfish.idlj.CORBAStruct[] test_seq (org.glassfish.idlj.CORBASeqHolder seq);
  int[] test_long_seq (org.glassfish.idlj.LongSeqHolder seq);
  org.omg.CORBA.Object test_POA (String name);
  void cleanup_POA (String name);
} // interface CORBAServerTestOperations
