package org.glassfish.idlj;


/**
* org/glassfish/idlj/CORBAEnumHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "4.1"
* from /Users/rgold/projects/glassfish/glassfish-corba/idlj/src/main/idl/org/glassfish/idlj/CORBAServerTest.idl
* Monday, January 29, 2018 11:19:41 AM EST
*/

abstract public class CORBAEnumHelper
{
  private static String  _id = "IDL:org/glassfish/idlj/CORBAEnum:1.0";

  public static void insert (org.omg.CORBA.Any a, org.glassfish.idlj.CORBAEnum that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static org.glassfish.idlj.CORBAEnum extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (org.glassfish.idlj.CORBAEnumHelper.id (), "CORBAEnum", new String[] { "ONE", "TWO", "THREE"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static org.glassfish.idlj.CORBAEnum read (org.omg.CORBA.portable.InputStream istream)
  {
    return org.glassfish.idlj.CORBAEnum.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, org.glassfish.idlj.CORBAEnum value)
  {
    ostream.write_long (value.value ());
  }

}
