package org.glassfish.idlj;


/**
* org/glassfish/idlj/CORBASeqHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "4.1"
* from /Users/rgold/projects/glassfish/glassfish-corba/idlj/src/main/idl/org/glassfish/idlj/CORBAServerTest.idl
* Monday, January 29, 2018 11:19:41 AM EST
*/

abstract public class CORBASeqHelper
{
  private static String  _id = "IDL:org/glassfish/idlj/CORBASeq:1.0";

  public static void insert (org.omg.CORBA.Any a, org.glassfish.idlj.CORBAStruct[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static org.glassfish.idlj.CORBAStruct[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.glassfish.idlj.CORBAStructHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (org.glassfish.idlj.CORBASeqHelper.id (), "CORBASeq", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static org.glassfish.idlj.CORBAStruct[] read (org.omg.CORBA.portable.InputStream istream)
  {
    org.glassfish.idlj.CORBAStruct value[] = null;
    int _len0 = istream.read_long ();
    value = new org.glassfish.idlj.CORBAStruct[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = org.glassfish.idlj.CORBAStructHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, org.glassfish.idlj.CORBAStruct[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      org.glassfish.idlj.CORBAStructHelper.write (ostream, value[_i0]);
  }

}
