package org.glassfish.idlj;


/**
* org/glassfish/idlj/CORBAEnum.java .
* Generated by the IDL-to-Java compiler (portable), version "4.1"
* from /Users/rgold/projects/glassfish/glassfish-corba/idlj/src/main/idl/org/glassfish/idlj/CORBAServerTest.idl
* Monday, January 29, 2018 11:19:41 AM EST
*/

public class CORBAEnum implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 3;
  private static org.glassfish.idlj.CORBAEnum[] __array = new org.glassfish.idlj.CORBAEnum [__size];

  public static final int _ONE = 0;
  public static final org.glassfish.idlj.CORBAEnum ONE = new org.glassfish.idlj.CORBAEnum(_ONE);
  public static final int _TWO = 1;
  public static final org.glassfish.idlj.CORBAEnum TWO = new org.glassfish.idlj.CORBAEnum(_TWO);
  public static final int _THREE = 2;
  public static final org.glassfish.idlj.CORBAEnum THREE = new org.glassfish.idlj.CORBAEnum(_THREE);

  public int value ()
  {
    return __value;
  }

  public static org.glassfish.idlj.CORBAEnum from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected CORBAEnum (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class CORBAEnum
