package org.glassfish.idlj;


/**
* org/glassfish/idlj/CORBAUnion.java .
* Generated by the IDL-to-Java compiler (portable), version "4.1"
* from /Users/rgold/projects/glassfish/glassfish-corba/idlj/src/main/idl/org/glassfish/idlj/CORBAServerTest.idl
* Monday, January 29, 2018 11:19:41 AM EST
*/

public final class CORBAUnion implements org.omg.CORBA.portable.IDLEntity
{
  private boolean ___b;
  private String ___w;
  private String ___s;
  private org.omg.CORBA.Any ___a;
  private org.glassfish.idlj.CORBAStruct ___cs;
  private long ___lll;
  private int __discriminator;
  private boolean __uninitialized = true;

  public CORBAUnion ()
  {
  }

  public int discriminator ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    return __discriminator;
  }

  public boolean b ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifyb (__discriminator);
    return ___b;
  }

  public void b (boolean value)
  {
    __discriminator = 0;
    ___b = value;
    __uninitialized = false;
  }

  public void b (int discriminator, boolean value)
  {
    verifyb (discriminator);
    __discriminator = discriminator;
    ___b = value;
    __uninitialized = false;
  }

  private void verifyb (int discriminator)
  {
    if (discriminator != 0)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

  public String w ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifyw (__discriminator);
    return ___w;
  }

  public void w (String value)
  {
    __discriminator = 1;
    ___w = value;
    __uninitialized = false;
  }

  public void w (int discriminator, String value)
  {
    verifyw (discriminator);
    __discriminator = discriminator;
    ___w = value;
    __uninitialized = false;
  }

  private void verifyw (int discriminator)
  {
    if (discriminator != 1)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

  public String s ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifys (__discriminator);
    return ___s;
  }

  public void s (String value)
  {
    __discriminator = 2;
    ___s = value;
    __uninitialized = false;
  }

  public void s (int discriminator, String value)
  {
    verifys (discriminator);
    __discriminator = discriminator;
    ___s = value;
    __uninitialized = false;
  }

  private void verifys (int discriminator)
  {
    if (discriminator != 2)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

  public org.omg.CORBA.Any a ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifya (__discriminator);
    return ___a;
  }

  public void a (org.omg.CORBA.Any value)
  {
    __discriminator = 3;
    ___a = value;
    __uninitialized = false;
  }

  public void a (int discriminator, org.omg.CORBA.Any value)
  {
    verifya (discriminator);
    __discriminator = discriminator;
    ___a = value;
    __uninitialized = false;
  }

  private void verifya (int discriminator)
  {
    if (discriminator != 3)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

  public org.glassfish.idlj.CORBAStruct cs ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifycs (__discriminator);
    return ___cs;
  }

  public void cs (org.glassfish.idlj.CORBAStruct value)
  {
    __discriminator = 4;
    ___cs = value;
    __uninitialized = false;
  }

  public void cs (int discriminator, org.glassfish.idlj.CORBAStruct value)
  {
    verifycs (discriminator);
    __discriminator = discriminator;
    ___cs = value;
    __uninitialized = false;
  }

  private void verifycs (int discriminator)
  {
    if (discriminator != 4)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

  public long lll ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifylll (__discriminator);
    return ___lll;
  }

  public void lll (long value)
  {
    __discriminator = -2147483648;
    ___lll = value;
    __uninitialized = false;
  }

  public void lll (int discriminator, long value)
  {
    verifylll (discriminator);
    __discriminator = discriminator;
    ___lll = value;
    __uninitialized = false;
  }

  private void verifylll (int discriminator)
  {
    if (discriminator == 0 || discriminator == 1 || discriminator == 2 || discriminator == 3 || discriminator == 4)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

} // class CORBAUnion
