package org.glassfish.idlj;


/**
* org/glassfish/idlj/CORBAStruct.java .
* Generated by the IDL-to-Java compiler (portable), version "4.1"
* from /Users/rgold/projects/glassfish/glassfish-corba/idlj/src/main/idl/org/glassfish/idlj/CORBAServerTest.idl
* Monday, January 29, 2018 11:19:41 AM EST
*/

public final class CORBAStruct implements org.omg.CORBA.portable.IDLEntity
{
  public int l = (int)0;
  public long lll = (long)0;

  // The name is 3 chars long to avoid a JDK alignment bug.
  public String s = null;
  public org.omg.CORBA.Any a = null;

  public CORBAStruct ()
  {
  } // ctor

  public CORBAStruct (int _l, long _lll, String _s, org.omg.CORBA.Any _a)
  {
    l = _l;
    lll = _lll;
    s = _s;
    a = _a;
  } // ctor

} // class CORBAStruct
