package org.glassfish.idlj;


/**
* org/glassfish/idlj/DummyCORBAServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "4.1"
* from /Users/rgold/projects/glassfish/glassfish-corba/idlj/src/main/idl/org/glassfish/idlj/CORBAServerTest.idl
* Monday, January 29, 2018 11:19:41 AM EST
*/

public interface DummyCORBAServerOperations 
{
} // interface DummyCORBAServerOperations
