/*
 * Copyright (c) 1997, 2018 Oracle and/or its affiliates. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Distribution License v. 1.0, which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

package com.sun.org.omg.CORBA;

/**
 * com/sun/org/omg/CORBA/AttributeDescription.java Generated by the IDL-to-Java compiler (portable), version "3.0" from
 * ir.idl Thursday, May 6, 1999 1:51:50 AM PDT
 */

public final class AttributeDescription implements org.omg.CORBA.portable.IDLEntity {
    public String name = null;
    public String id = null;
    public String defined_in = null;
    public String version = null;
    public org.omg.CORBA.TypeCode type = null;
    public com.sun.org.omg.CORBA.AttributeMode mode = null;

    public AttributeDescription() {
    } // ctor

    public AttributeDescription(String _name, String _id, String _defined_in, String _version, org.omg.CORBA.TypeCode _type,
            com.sun.org.omg.CORBA.AttributeMode _mode) {
        name = _name;
        id = _id;
        defined_in = _defined_in;
        version = _version;
        type = _type;
        mode = _mode;
    } // ctor

} // class AttributeDescription
