/*
 * Copyright (c) 1997, 2018 Oracle and/or its affiliates. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Distribution License v. 1.0, which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

package com.sun.org.omg.CORBA;


/**
* com/sun/org/omg/CORBA/IDLTypeOperations.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from ir.idl
* Thursday, May 6, 1999 1:51:45 AM PDT
*/

public interface IDLTypeOperations  extends com.sun.org.omg.CORBA.IRObjectOperations
{
    org.omg.CORBA.TypeCode type ();
} // interface IDLTypeOperations
