/*
 * Copyright (c) 1997, 2020 Oracle and/or its affiliates.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0, or the Eclipse Distribution License
 * v. 1.0 which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License v. 2.0 are satisfied: GNU General Public License v2.0
 * w/Classpath exception which is available at
 * https://www.gnu.org/software/classpath/license.html.
 *
 * SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause OR GPL-2.0 WITH
 * Classpath-exception-2.0
 */

package com.sun.org.omg.CORBA;

/**
 * com/sun/org/omg/CORBA/OperationModeHelper.java Generated by the IDL-to-Java compiler (portable), version "3.0" from
 * ir.idl Thursday, May 6, 1999 1:51:50 AM PDT
 */

public final class OperationModeHelper {
    private static String _id = "IDL:omg.org/CORBA/OperationMode:1.0";

    public OperationModeHelper() {
    }

    public static void insert(org.omg.CORBA.Any a, com.sun.org.omg.CORBA.OperationMode that) {
        org.omg.CORBA.portable.OutputStream out = a.create_output_stream();
        a.type(type());
        write(out, that);
        a.read_value(out.create_input_stream(), type());
    }

    public static com.sun.org.omg.CORBA.OperationMode extract(org.omg.CORBA.Any a) {
        return read(a.create_input_stream());
    }

    private static org.omg.CORBA.TypeCode __typeCode = null;

    synchronized public static org.omg.CORBA.TypeCode type() {
        if (__typeCode == null) {
            __typeCode = org.omg.CORBA.ORB.init().create_enum_tc(com.sun.org.omg.CORBA.OperationModeHelper.id(), "OperationMode",
                    new String[] { "OP_NORMAL", "OP_ONEWAY" });
        }
        return __typeCode;
    }

    public static String id() {
        return _id;
    }

    public static com.sun.org.omg.CORBA.OperationMode read(org.omg.CORBA.portable.InputStream istream) {
        return com.sun.org.omg.CORBA.OperationMode.from_int(istream.read_long());
    }

    public static void write(org.omg.CORBA.portable.OutputStream ostream, com.sun.org.omg.CORBA.OperationMode value) {
        ostream.write_long(value.value());
    }

}
