// Tie class generated by rmic, do not edit.
// Contents subject to change without notice.

package org.glassfish.rmic.classes.hcks;

import java.io.Serializable;
import java.rmi.Remote;
import java.rmi.RemoteException;
import javax.rmi.CORBA.Tie;
import javax.rmi.CORBA.Util;
import org.omg.CORBA.BAD_OPERATION;
import org.omg.CORBA.ORB;
import org.omg.CORBA.SystemException;
import org.omg.CORBA.portable.InputStream;
import org.omg.CORBA.portable.OutputStream;
import org.omg.CORBA.portable.ResponseHandler;
import org.omg.CORBA.portable.UnknownException;
import org.omg.PortableServer.Servant;


public class _RmiIIServantPOA_Tie extends Servant implements Tie {
    
    volatile private RmiIIServantPOA target = null;
    
    private static final String[] _type_ids = {
        "RMI:org.glassfish.rmic.classes.hcks.RmiII:0000000000000000"
    };
    
    public void setTarget(Remote target) {
        this.target = (RmiIIServantPOA) target;
    }
    
    public Remote getTarget() {
        return target;
    }
    
    public org.omg.CORBA.Object thisObject() {
        return _this_object();
    }
    
    public void deactivate() {
        try{
        _poa().deactivate_object(_poa().servant_to_id(this));
        }catch (org.omg.PortableServer.POAPackage.WrongPolicy exception){
        
        }catch (org.omg.PortableServer.POAPackage.ObjectNotActive exception){
        
        }catch (org.omg.PortableServer.POAPackage.ServantNotActive exception){
        
        }
    }
    
    public ORB orb() {
        return _orb();
    }
    
    public void orb(ORB orb) {
        try {
            ((org.omg.CORBA_2_3.ORB)orb).set_delegate(this);
        }
        catch(ClassCastException e) {
            throw new org.omg.CORBA.BAD_PARAM
                ("POA Servant requires an instance of org.omg.CORBA_2_3.ORB");
        }
    }
    
    public String[] _all_interfaces(org.omg.PortableServer.POA poa, byte[] objectId){
        return (String[]) _type_ids.clone();
    }
    
    public OutputStream  _invoke(String method, InputStream _in, ResponseHandler reply) throws SystemException {
        try {
            RmiIIServantPOA target = this.target;
            if (target == null) {
                throw new java.io.IOException();
            }
            org.omg.CORBA_2_3.portable.InputStream in = 
                (org.omg.CORBA_2_3.portable.InputStream) _in;
            switch (method.length()) {
                case 8: 
                    if (method.equals("sayHello")) {
                        String result = target.sayHello();
                        org.omg.CORBA_2_3.portable.OutputStream out = 
                            (org.omg.CORBA_2_3.portable.OutputStream) reply.createReply();
                        out.write_value(result,String.class);
                        return out;
                    }
                case 9: 
                    if (method.equals("sendBytes")) {
                        byte[] arg0 = (byte[]) in.read_value(byte[].class);
                        int result = target.sendBytes(arg0);
                        OutputStream out = reply.createReply();
                        out.write_long(result);
                        return out;
                    }
                case 13: 
                    if (method.equals("sendOneObject")) {
                        Object arg0 = Util.readAny(in);
                        Object result;
                        try {
                            result = target.sendOneObject(arg0);
                        } catch (RmiIMyException ex) {
                            String id = "IDL:org/glassfish/rmic/classes/hcks/RmiIMyEx:1.0";
                            org.omg.CORBA_2_3.portable.OutputStream out = 
                                (org.omg.CORBA_2_3.portable.OutputStream) reply.createExceptionReply();
                            out.write_string(id);
                            out.write_value(ex,RmiIMyException.class);
                            return out;
                        }
                        OutputStream out = reply.createReply();
                        Util.writeAny(out,result);
                        return out;
                    }
                case 14: 
                    if (method.equals("sendTwoObjects")) {
                        Object arg0 = Util.readAny(in);
                        Object arg1 = Util.readAny(in);
                        Object result = target.sendTwoObjects(arg0, arg1);
                        OutputStream out = reply.createReply();
                        Util.writeAny(out,result);
                        return out;
                    }
                case 22: 
                    if (method.equals("returnObjectFromServer")) {
                        boolean arg0 = in.read_boolean();
                        Object result = target.returnObjectFromServer(arg0);
                        OutputStream out = reply.createReply();
                        Util.writeAny(out,result);
                        return out;
                    }
                case 24: 
                    if (method.equals("colocatedCallFromServant")) {
                        String arg0 = (String) in.read_value(String.class);
                        String result = target.colocatedCallFromServant(arg0);
                        org.omg.CORBA_2_3.portable.OutputStream out = 
                            (org.omg.CORBA_2_3.portable.OutputStream) reply.createReply();
                        out.write_value(result,String.class);
                        return out;
                    }
                case 25: 
                    if (method.equals("throwThreadDeathInServant")) {
                        String arg0 = (String) in.read_value(String.class);
                        String result = target.throwThreadDeathInServant(arg0);
                        org.omg.CORBA_2_3.portable.OutputStream out = 
                            (org.omg.CORBA_2_3.portable.OutputStream) reply.createReply();
                        out.write_value(result,String.class);
                        return out;
                    }
                case 28: 
                    if (method.equals("makeColocatedCallFromServant")) {
                        String result = target.makeColocatedCallFromServant();
                        org.omg.CORBA_2_3.portable.OutputStream out = 
                            (org.omg.CORBA_2_3.portable.OutputStream) reply.createReply();
                        out.write_value(result,String.class);
                        return out;
                    }
            }
            throw new BAD_OPERATION();
        } catch (SystemException ex) {
            throw ex;
        } catch (Throwable ex) {
            throw new UnknownException(ex);
        }
    }
}
