/*
 * Copyright (c) 1997, 2018 Oracle and/or its affiliates. All rights reserved.
 * Copyright (c) 1998-1999 IBM Corp. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Distribution License v. 1.0, which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

package rmic;


/**
* rmic/CORBAUserExceptionHelper.java
* Generated by the IBM IDL-to-Java compiler (portable), version "3.0"
* from cue.idl
* 09 May 1999 11:07:10 o'clock GMT+00:00
*/

public final class CORBAUserExceptionHelper
{
    private static String  _id = "IDL:rmic/CORBAUserException:1.0";

    public CORBAUserExceptionHelper()
    {
    }

    public static void insert (org.omg.CORBA.Any a, rmic.CORBAUserException that)
    {
        org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
        a.type (type ());
        write (out, that);
        a.read_value (out.create_input_stream (), type ());
    }

    public static rmic.CORBAUserException extract (org.omg.CORBA.Any a)
    {
        return read (a.create_input_stream ());
    }

    private static org.omg.CORBA.TypeCode __typeCode = null;
    private static boolean __active = false;
    synchronized public static org.omg.CORBA.TypeCode type ()
    {
        if (__typeCode == null)
            {
                synchronized (org.omg.CORBA.TypeCode.class)
                    {
                        if (__typeCode == null)
                            {
                                if (__active)
                                    {
                                        return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
                                    }
                                __active = true;
                                org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [0];
                                org.omg.CORBA.TypeCode _tcOf_members0 = null;
                                __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (rmic.CORBAUserExceptionHelper.id (), "CORBAUserException", _members0);
                                __active = false;
                            }
                    }
            }
        return __typeCode;
    }

    public static String id ()
    {
        return _id;
    }

    public static rmic.CORBAUserException read (org.omg.CORBA.portable.InputStream istream)
    {
        rmic.CORBAUserException value = new rmic.CORBAUserException ();
        // read and discard the repository ID
        istream.read_string ();
        return value;
    }

    public static void write (org.omg.CORBA.portable.OutputStream ostream, rmic.CORBAUserException value)
    {
        // write the repository ID
        ostream.write_string (id ());
    }

}
