/*
 * Copyright (c) 1997, 2018 Oracle and/or its affiliates. All rights reserved.
 * Copyright (c) 1998-1999 IBM Corp. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Distribution License v. 1.0, which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

package rmic;


/**
* rmic/CORBAUserException2.java
* Generated by the IBM IDL-to-Java compiler (portable), version "3.0"
* from cue.idl
* Monday, May 10, 1999 12:31:06 o'clock PM PDT
*/

public final class CORBAUserException2 extends org.omg.CORBA.UserException implements org.omg.CORBA.portable.IDLEntity
{

    public CORBAUserException2 ()
    {
    } // ctor

} // class CORBAUserException2
