/*
 * Copyright (c) 1997, 2018 Oracle and/or its affiliates. All rights reserved.
 * Copyright (c) 1998-1999 IBM Corp. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Distribution License v. 1.0, which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

package omega;


/**
* omega/Climax.java
* Generated by the IBM IDL-to-Java compiler (portable), version "3.0"
* from d:/java/java/idl/omega/Lima.idl
* 06 May 1999 17:02:50 o'clock GMT+00:00
*/

public final class Climax extends org.omg.CORBA.UserException implements org.omg.CORBA.portable.IDLEntity
{
    public int quickstep = (int)0;

    public Climax ()
    {
    } // ctor

    public Climax (int _quickstep)
    {
        quickstep = _quickstep;
    } // ctor

} // class Climax
