/*
 * Copyright (c) 1997, 2018 Oracle and/or its affiliates. All rights reserved.
 * Copyright (c) 1998-1999 IBM Corp. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Distribution License v. 1.0, which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

package omega;


/**
* genJava/omega/Foxtrot.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from d:/java/java/idl/omega/Foxtrot.idl
* 22 April 1999 21:50:01 o'clock GMT+00:00
*/

public final class Foxtrot implements org.omg.CORBA.portable.IDLEntity
{
    public int tango = (int)0;
    public int uniform = (int)0;
    public int quickstep = (int)0;

    public Foxtrot ()
    {
    } // ctor

    public Foxtrot (int _tango, int _uniform, int _quickstep)
    {
        tango = _tango;
        uniform = _uniform;
        quickstep = _quickstep;
    } // ctor

} // class Foxtrot
