/*
 * Copyright (c) 1997, 2018 Oracle and/or its affiliates. All rights reserved.
 * Copyright (c) 1998-1999 IBM Corp. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Distribution License v. 1.0, which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

package omega;


/**
* genJava/omega/Hotel.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from d:/java/java/idl/omega/Hotel.idl
* 22 April 1999 22:03:20 o'clock GMT+00:00
*/

public class Hotel implements org.omg.CORBA.portable.ValueBase
{
    public int tango = (int)0;
    public int quickstep = (int)0;

    public  Hotel ()
    {
    }

    public String[] _truncatable_ids() {
        return omega.HotelHelper.get_instance().get_truncatable_base_ids();
    }

    public void dolength (int length)
    {
    }

} // class Hotel
