/*
 * Copyright (c) 1997, 2020 Oracle and/or its affiliates.
 * Copyright (c) 1998-1999 IBM Corp. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0, or the Eclipse Distribution License
 * v. 1.0 which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License v. 2.0 are satisfied: GNU General Public License v2.0
 * w/Classpath exception which is available at
 * https://www.gnu.org/software/classpath/license.html.
 *
 * SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause OR GPL-2.0 WITH
 * Classpath-exception-2.0
 */

package omega;


/**
* genJava/omega/HotelHelper.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from d:/java/java/idl/omega/Hotel.idl
* 22 April 1999 22:03:19 o'clock GMT+00:00
*/

public final class HotelHelper implements com.sun.org.omg.CORBA.portable.ValueHelper
{
    private static String  _id = "IDL:omega/Hotel:1.0";

    private static HotelHelper helper = new HotelHelper ();

    private static String[] _truncatable_ids = {
        _id   };

    public HotelHelper()
    {
    }

    public static void insert (org.omg.CORBA.Any a, omega.Hotel that)
    {
        org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
        a.type (type ());
        write (out, that);
        a.read_value (out.create_input_stream (), type ());
    }

    public static omega.Hotel extract (org.omg.CORBA.Any a)
    {
        return read (a.create_input_stream ());
    }

    private static org.omg.CORBA.TypeCode __typeCode = null;
    private static boolean __active = false;
    synchronized public static org.omg.CORBA.TypeCode type ()
    {
        if (__typeCode == null)
            {
                synchronized (org.omg.CORBA.TypeCode.class)
                    {
                        if (__typeCode == null)
                            {
                                if (__active)
                                    {
                                        return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
                                    }
                                __active = true;
                                org.omg.CORBA.ValueMember[] _members0 = new org.omg.CORBA.ValueMember[2];
                                org.omg.CORBA.TypeCode _tcOf_members0 = null;

                                // ValueMember instance for tango
                                _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
                                _members0[0] = new org.omg.CORBA.ValueMember ("tango", 
                                                                              "", 
                                                                              _id, 
                                                                              "", 
                                                                              _tcOf_members0, 
                                                                              null, 
                                                                              org.omg.CORBA.PUBLIC_MEMBER.value);

                                // ValueMember instance for quickstep
                                _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
                                _members0[1] = new org.omg.CORBA.ValueMember ("quickstep", 
                                                                              "", 
                                                                              _id, 
                                                                              "", 
                                                                              _tcOf_members0, 
                                                                              null, 
                                                                              org.omg.CORBA.PUBLIC_MEMBER.value);

                                __typeCode = org.omg.CORBA.ORB.init ().create_value_tc (_id, "Hotel", org.omg.CORBA.VM_NONE.value, null, _members0);
                                __active = false;
                            }
                    }
            }
        return __typeCode;
    }

    public static String id ()
    {
        return _id;
    }

    public static omega.Hotel read (org.omg.CORBA.portable.InputStream istream)
    {
        return (omega.Hotel) ((org.omg.CORBA_2_3.portable.InputStream) istream).read_value (get_instance());
    }

    public java.io.Serializable read_value (org.omg.CORBA.portable.InputStream istream)
    {
        omega.Hotel value = new omega.Hotel ();
        value.tango = istream.read_long ();
        value.quickstep = istream.read_long ();
        return value;
    }

    public static void read (org.omg.CORBA.portable.InputStream istream, omega.Hotel value)
    {
        value.tango = istream.read_long ();
        value.quickstep = istream.read_long ();
    }

    public static void write (org.omg.CORBA.portable.OutputStream ostream, omega.Hotel value)
    {
        ((org.omg.CORBA_2_3.portable.OutputStream) ostream).write_value (value, get_instance());
    }

    public void write_value (org.omg.CORBA.portable.OutputStream ostream, java.io.Serializable obj)
    {
        omega.Hotel value  = (omega.Hotel) obj;
        ostream.write_long (value.tango);
        ostream.write_long (value.quickstep);
    }

    public String get_id ()
    {
        return _id;
    }

    public org.omg.CORBA.TypeCode get_type ()
    {
        return type ();
    }

    public static com.sun.org.omg.CORBA.portable.ValueHelper get_instance ()
    {
        return helper;
    }

    public Class get_class ()
    {
        return omega.Hotel.class;
    }

    public String[] get_truncatable_base_ids ()
    {
        return _truncatable_ids;
    }

}
