/*
 * Copyright (c) 1997, 2018 Oracle and/or its affiliates. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Distribution License v. 1.0, which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

package hopper.h4670827;

import test.Test;
import corba.framework.*;
import java.util.*;

/**
 * This is a test for INS.
 */
public class INSTest extends CORBATest
{
    public static String[] idlFiles = { "hello.idl" };

    // Define the .java files that need to be compiled.  Any
    // java files generated by compiling IDL will automatically be
    // compiled with these.
    public static String[] javaFiles = {"Client.java", 
                                        "HelloImpl.java",
                                        "INSServer.java"};

    // This is the main method defining the test.  All tests
    // should have this.
    protected void doTest() throws Throwable
    {
        Options.addIDLCompilerArgs( "-fall -oldImplBase" );
        Options.setJavaFiles(javaFiles);
        Options.setIDLFiles(idlFiles);

        compileIDLFiles();

        compileJavaFiles();

        Controller client = createClient("hopper.h4670827.Client");
 
        Object serverExtras[] = new Object[3];

        Hashtable serverExtra = Options.getServerExtra();
        serverExtra.put("client", client);

        Controller server
            = createServer("hopper.h4670827.INSServer");


        // Server starts the client and does a waitFor
        server.start();

        Thread.sleep(10000);

        client.start();

        Thread.sleep(10000);

        // Make sure all the processes are shut down.
        server.stop();
        client.stop();
    }
}

